---
- hosts: all
  tasks:
 
  - name: install apache2 package
    apt:
      name: apache2
      state: latest

  - name: add php for apache
    apt:
      name: libapache2-mod-php
      state: latest  
